services:
  Roman:
    container_name: Roman_Container
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    entrypoint: [ 'java', '-Xmx512m' ,  '-Djava.util.concurrent.ForkJoinPool.common.parallelism=50',
                  '-cp', '/classpath/*:/libs/*', 'com.adobe.romannumeral.App' ]
    environment:
      HTTP_PORT: '8080'
    expose:
      - 8080
      - 9090
    image: romannumeral:latest
    labels:
      app: roman
    ports:
      - '8080'
      - '9090'
version: '3'